#!/usr/bin/env python3
"""
OneRuler-OELLM adapter for base-LM scoring.

Reads OneRuler NIAH JSONL examples (generated by run_oellm_mini_eval.py
with --backend huggingface or the dataset JSONL), converts each instruction
prompt into a base-LM completion prefix, and scores candidate answers by
log-likelihood instead of generation.

Input JSONL format (OneRuler output or dataset):
  {
    "input":   "...<long context>...\n\nQuestion: ...\nAnswer:",
    "outputs": ["correct_answer", "distractor1", "distractor2", ...],
    "label":   0   # index of correct answer in outputs
  }

Output JSONL:
  {
    ... original fields ...,
    "scores":    [logprob_for_each_output],
    "pred_idx":  argmax_idx,
    "correct":   bool
  }

Usage
-----
  python oneruler_score_base_lm.py \\
      --model  /flash/.../converted/checkpoint_0001000 \\
      --input  /scratch/.../eval-oneruler-smoke/4k/fr_results.jsonl \\
      --output /scratch/.../eval-base-lm-oneruler/4k_fr.jsonl

  # All files at once:
  for f in /scratch/.../eval-oneruler-smoke/**/*.jsonl; do
      python oneruler_score_base_lm.py --model ... --input "$f" --output scored_"$(basename $f)"
  done

Prefix extraction
-----------------
OneRuler instruction prompts typically end with:
  "Answer: <Answer>"   (instruction format)
This adapter strips everything from the last "Answer:" onward and uses
  "<context>\n\n<question prefix>\nThe answer is:"
as the completion prefix — a natural base-LM stub requiring no SFT.
"""

import argparse
import json
import re
import sys
from pathlib import Path

import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer


def extract_prefix(instruction_prompt: str) -> str:
    """
    Convert an instruction-style prompt to a base-LM completion prefix.

    Strips instruction answer format and replaces with a neutral stub.
    """
    # Remove trailing whitespace / answer tags
    text = instruction_prompt.strip()
    text = re.sub(r"<Answer>.*", "", text, flags=re.DOTALL).strip()
    text = re.sub(r"\nAnswer:.*$", "", text, flags=re.DOTALL).strip()
    text = re.sub(r"\nPlease answer.*$", "", text, flags=re.DOTALL).strip()
    # Append a neutral completion stub
    return text + "\nThe answer is:"


def score_completion(model, tokenizer, prefix: str, candidate: str, device) -> float:
    """Sum of log P(candidate tokens | prefix) under the model."""
    full = prefix + " " + candidate.strip()
    enc_full = tokenizer(full, return_tensors="pt", truncation=False).to(device)
    enc_pre = tokenizer(prefix, return_tensors="pt", truncation=False).to(device)
    pre_len = enc_pre["input_ids"].shape[1]

    with torch.no_grad():
        out = model(**enc_full)

    lp = F.log_softmax(out.logits[0], dim=-1)
    ids = enc_full["input_ids"][0][pre_len:]
    if len(ids) == 0:
        return float("-inf")
    return sum(lp[pre_len - 1 + j, ids[j]].item() for j in range(len(ids)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model",  required=True, help="HF model directory")
    ap.add_argument("--input",  required=True, help="OneRuler JSONL file")
    ap.add_argument("--output", required=True, help="Scored JSONL output path")
    ap.add_argument("--max-examples", type=int, default=None)
    args = ap.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}", flush=True)

    print("Loading tokenizer...", flush=True)
    tok = AutoTokenizer.from_pretrained(args.model)

    print("Loading model...", flush=True)
    model = AutoModelForCausalLM.from_pretrained(
        args.model, torch_dtype=torch.bfloat16, device_map="auto"
    )
    model.eval()
    print("Ready.\n", flush=True)

    in_path = Path(args.input)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    examples = [json.loads(l) for l in in_path.read_text().splitlines() if l.strip()]
    if args.max_examples:
        examples = examples[:args.max_examples]

    correct = 0
    with open(out_path, "w") as fout:
        for i, ex in enumerate(examples):
            prompt   = ex.get("input", ex.get("prompt", ""))
            outputs  = ex.get("outputs", ex.get("candidates", []))
            label    = ex.get("label", ex.get("true_idx", 0))

            prefix = extract_prefix(prompt)
            scores = [score_completion(model, tok, prefix, c, device) for c in outputs]
            pred = int(max(range(len(scores)), key=lambda j: scores[j]))
            ok   = pred == label

            result = {**ex, "scores": scores, "pred_idx": pred, "correct": ok}
            fout.write(json.dumps(result, ensure_ascii=False) + "\n")
            correct += ok
            print(f"  [{i+1}/{len(examples)}] correct={ok}  pred={outputs[pred]!r}  "
                  f"true={outputs[label]!r}", flush=True)

    acc = correct / len(examples) if examples else 0.0
    print(f"\nAccuracy: {correct}/{len(examples)} = {acc:.2%}")
    print(f"Output:   {out_path}")


if __name__ == "__main__":
    main()
